name: one_go_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-255.2.beta <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.2.0
  flutter_screenutil: 5.4.0
  introduction_screen: ^3.0.2
  country_code_picker: ^2.0.2
  form_validator: ^1.0.2
  form_field_validator: ^1.1.0
  flutter_svg: ^1.1.0
  modal_progress_hud_nsn: ^0.2.1
  http: ^0.13.5
  flutter_launcher_icons: ^0.9.3
  provider: ^6.0.3
  flutter_native_splash: ^2.2.7
  page_transition: ^2.0.9
  shared_preferences: ^2.0.15
  google_fonts: ^3.0.1
  pin_code_fields: ^7.4.0
  dropdown_button2: ^1.9.2
  google_maps_flutter: ^2.2.2
  location: ^4.4.0
  figma_squircle: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/figma_pngs/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700